# 01 Numpy (Numerical Python)

In [1]:
# de facto standard (사실상의 표준)
import numpy as np

In [5]:
a = [1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [6]:
list(map(lambda x: 3*x, a))

[3, 6, 9]

In [8]:
b = np.array([1,2,3])
b*3

array([3, 6, 9])

## 1. Numpy Dimensional array

In [10]:
a = np.array([1,2,3,4],float)
a

array([1., 2., 3., 4.])

In [11]:
a.dtype, a.shape   #(4,) -> 1차원 벡터 [1,2,3,4] 
                               #(2,3) -> 2차원 벡터 [[1,2,3],
                                                     [4,5,6]]

(dtype('float64'), (4,))

## 2. Array shape

In [12]:
# Vector(1차원)
vec = np.array([1,2,3])
vec.shape

(3,)

In [15]:
# Matrix(2차원)
mat = np.array([[1,2,3],[4,5,6]])
mat.shape
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# Tensor(3차원 이상)
ten = np.arange(1,25).reshape(2,3,4)
print(ten)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [17]:
ten.shape

(2, 3, 4)

In [18]:
# element 갯수
vec.size, mat.size, ten.size

(3, 6, 24)

In [19]:
# data type
# float 32 : 32bit로 표시 - single precision
# float 64 : 64bit로 표시 - double precision
a = np.array([1,2,3], np.float32)
a

array([1., 2., 3.], dtype=float32)

In [21]:
b = np.array([1,2,3],dtype = np.int32)
b

array([1, 2, 3], dtype=int32)

## reshape

In [22]:
mat.shape

(2, 3)

In [23]:
mat.reshape(6,)

array([1, 2, 3, 4, 5, 6])

In [26]:
mat.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
# -1은 numpy가 알아서 맞춰줌 (딘, size가 동일)
mat.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [28]:
mat.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
mat.reshape(3,-1).shape

(3, 2)

In [31]:
ten.shape(2,-1,-1).shape # -1을 2개는 안된다.

TypeError: ignored

## flatten -> 1차원 변환

In [39]:
ten.reshape(-1,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [35]:
ten.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## 3. Indexing & Slicing

### Indexing

In [37]:
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
mat[0,1]

2

In [40]:
ten[1,1,2]

19

###slicing

In [43]:
b = np.arange(16).reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
# 5,6,9,10
b[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [45]:
# 5,6,7,9,10,11
b[1:3,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [47]:
# 1,3,9,11
b[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [50]:
X , y = b[:,:-1],b[:,-1] 

In [52]:
X,y

(array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]), array([ 3,  7, 11, 15]))